### ISSUE TITLE
Problems with submission

### ISSUE THREAD

**Issue by bm000** [faridcher/ml-course#1]
Hi, I've been having a problem with submission (please see below).

Do you have any idea why this might be happening?

Cheers
Bob

> source("submit.r")
> submit()
== Submitting solutions | Linear Regression with Multiple Variables... 
Login (email address): 
XXXXXX@hotmail.co.uk
token:
4BIEsjivD1WGjERU
!! Submission failed: unexpected error: gradientDescentMulti.R:29:1: unexpected '}'
28:   list(theta = theta, J_history = J_history)
29: }
   ^
!! Please try again later.
Error in response$errorMessage : 
  object of type 'special' is not subsettable
>

**Comment by faridcher** [comment]
It is hard to guess what is the root of this problem. I just resubmitted the first assignment and no problem happened. So, there is no problem with submission code. there is probably a problem in your `gradientDescentMulti.R` code which produces the wrong results. To solve it, compare your answer with the one in the `solutions` folder.

**Comment by bm000** [comment]
Thanks for your quick response! I actually haven't made any changes to gradientDescentMulti.R, maybe this is the problem? I assumed you could submit at each stage of the assignment but should I only do it at the end?

Many thanks for your time.

**Comment by faridcher** [comment]
You should first complete all stages of a single exercise and then submit.
