### ISSUE TITLE
sigmoid function in assignment 3 needs to be completed

### ISSUE THREAD

**Issue by moritz4** [faridcher/ml-course#11]
Was getting a strange error in assignment 3. Turns out the sigmoid function in sigmoid.R is blank, but there is no * indicaated that it needs to be completed in the Introduction to the assignment https://github.com/faridcher/ml-course/wiki/3#introduction

**Comment by faridcher** [comment]
sigmoid function is already completed in exercise 2. So the sigmoid_solution.R should replace sigmoid.R

thank you for reporting this.
