### ISSUE TITLE
why Theta is called as a subfunction

### ISSUE THREAD

**Issue by rajasekhar-thiru** [faridcher/ml-course#4]
Hi Fared,
Curios to know why you create function within function (Theta as a subfunction of cost function). 
For example, 

linearRegCostFunction <- function(X, y, lambda) {
  function(theta) {

why not 
linearRegCostFunction <- function(X, y, lambda,theta) {
 
Is it just a coding style or there is a particular reason.

Thanks in advance.

**Comment by faridcher** [comment]
I wanted linearRegCostFunction to return a function instead of a value,
since the optim() function in R require a cost function as its second
argument. of course there other ways of doing this, but this is my
preferred style of coding for optimizations.
​
