### ISSUE TITLE
Submission error 

### ISSUE THREAD

**Issue by PROFAGAS** [faridcher/ml-course#8]
Hi 
First things first, thank you for this very good resource for leaarning maching learning. May the good lord continue to bless you.

However I have an error in running ex1.R.
I keep getting this error message below

Running warmUpExercise ... 
5x5 Identity Matrix: 
Error in warmUpExercise() : object 'A' not found

Any help.
Thanks

P.S I have tried this also.. same result

> source("D:/UIUC PHD/MACHINE LEARNING/COURSERA/EXERCISES/1/ex1.R")
Running warmUpExercise ... 
5x5 Identity Matrix: 
Error in warmUpExercise() : object 'A' not found

**Comment by faridcher** [comment]
You should complete the missing code in `warmUpExercise()` function. Take a look at the provided solution for that function i.e. `warmUpExercise_solution.R`.
